import { createHash } from 'node:crypto';
import { spawn } from 'node:child_process';
import {
  cp,
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rm,
  stat,
  writeFile,
} from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { basename, join, relative, resolve } from 'node:path';
import process from 'node:process';

const root = resolve(import.meta.dirname, '..');
const packageJson = JSON.parse(
  await readFile(join(root, 'package.json'), 'utf8'),
);
const platformArgument = process.argv.indexOf('--platform');
const platform =
  platformArgument < 0 ? process.platform : process.argv[platformArgument + 1];
if (platform !== 'windows' && platform !== 'linux') {
  throw new Error('--platform must be windows or linux');
}
const outputArgument = process.argv.indexOf('--output');
const output = resolve(
  root,
  outputArgument < 0 || process.argv[outputArgument + 1] === undefined
    ? 'artifacts/release'
    : process.argv[outputArgument + 1],
);
const archiveName = `kdenlive-mcp-${packageJson.version}-${platform}-x64`;
const stage = join(output, archiveName);

async function run(command, args) {
  await new Promise((resolvePromise, reject) => {
    const child = spawn(command, args, {
      cwd: root,
      shell: false,
      windowsHide: true,
      stdio: 'inherit',
      env: { ...process.env, CI: 'true' },
    });
    child.on('error', reject);
    child.on('close', (code) =>
      code === 0
        ? resolvePromise()
        : reject(new Error(`${command} exited with ${String(code)}`)),
    );
  });
}

async function files(directory) {
  const outputFiles = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) outputFiles.push(...(await files(path)));
    else if (entry.isFile()) outputFiles.push(path);
  }
  return outputFiles;
}

await mkdir(output, { recursive: true });
await rm(stage, { recursive: true, force: true });
await mkdir(join(stage, 'app'), { recursive: true });
const installRoot = await mkdtemp(join(tmpdir(), 'kdenlive-mcp-package-'));
await writeFile(
  join(installRoot, 'package.json'),
  `${JSON.stringify(
    {
      name: 'kdenlive-mcp-release',
      version: packageJson.version,
      private: true,
      type: 'module',
      dependencies: {
        '@modelcontextprotocol/sdk': '1.29.0',
        zod: '4.4.3',
      },
    },
    null,
    2,
  )}\n`,
  'utf8',
);
const pnpmCli = process.env.npm_execpath;
if (pnpmCli === undefined) throw new Error('Run this script through pnpm.');
await run(process.execPath, [
  pnpmCli,
  '--dir',
  installRoot,
  'add',
  '--prod',
  '--prefer-offline',
  '--ignore-scripts',
  '--force',
  '--config.node-linker=hoisted',
  '@modelcontextprotocol/sdk@1.29.0',
  'zod@4.4.3',
]);
await cp(join(installRoot, 'package.json'), join(stage, 'app', 'package.json'));
await cp(
  join(installRoot, 'pnpm-lock.yaml'),
  join(stage, 'app', 'pnpm-lock.yaml'),
);
await cp(
  join(installRoot, 'node_modules'),
  join(stage, 'app', 'node_modules'),
  {
    recursive: true,
  },
);
await rm(join(stage, 'app', 'node_modules', '.bin'), {
  recursive: true,
  force: true,
});
await rm(installRoot, { recursive: true, force: true });
await cp(join(root, 'apps', 'mcp-server', 'dist'), join(stage, 'app', 'dist'), {
  recursive: true,
});
for (const name of ['project-core', 'render-core', 'runtime-probe']) {
  const target = join(stage, 'app', 'node_modules', '@kdenlive-mcp', name);
  await mkdir(target, { recursive: true });
  await cp(join(root, 'packages', name, 'dist'), join(target, 'dist'), {
    recursive: true,
  });
  await cp(
    join(root, 'packages', name, 'package.json'),
    join(target, 'package.json'),
  );
}
for (const path of [
  'LICENSE',
  'README.md',
  'INSTALL.md',
  'SECURITY.md',
  'SUPPORT.md',
  'THIRD_PARTY_NOTICES.md',
]) {
  await cp(join(root, path), join(stage, path));
}
await cp(join(root, 'docs'), join(stage, 'docs'), { recursive: true });
await cp(join(root, 'config'), join(stage, 'config'), { recursive: true });
try {
  await cp(join(root, 'artifacts', 'licenses'), join(stage, 'licenses'), {
    recursive: true,
  });
} catch {
  // License inventory is generated by package:release; keep direct script use possible.
}
if (platform === 'windows') {
  await writeFile(
    join(stage, 'kdenlive-mcp.cmd'),
    '@echo off\r\nnode "%~dp0app\\dist\\cli.js" %*\r\n',
    'utf8',
  );
} else {
  await writeFile(
    join(stage, 'kdenlive-mcp'),
    '#!/usr/bin/env sh\nexec node "$(dirname "$0")/app/dist/cli.js" "$@"\n',
    { encoding: 'utf8', mode: 0o755 },
  );
}
const manifest = [];
for (const path of (await files(stage)).sort()) {
  const details = await stat(path);
  const hash = createHash('sha256')
    .update(await readFile(path))
    .digest('hex');
  manifest.push({
    path: relative(stage, path).replaceAll('\\', '/'),
    size: details.size,
    sha256: hash,
  });
}
await writeFile(
  join(stage, 'MANIFEST.json'),
  `${JSON.stringify({ schemaVersion: 1, name: archiveName, files: manifest }, null, 2)}\n`,
  'utf8',
);
const archive = join(
  output,
  `${archiveName}.${platform === 'windows' ? 'zip' : 'tar.gz'}`,
);
await rm(archive, { force: true });
await run('tar', [
  ...(platform === 'windows' ? ['-a', '-cf'] : ['-czf']),
  archive,
  '-C',
  output,
  basename(stage),
]);
const archiveHash = createHash('sha256')
  .update(await readFile(archive))
  .digest('hex');
await writeFile(
  `${archive}.sha256`,
  `${archiveHash}  ${basename(archive)}\n`,
  'utf8',
);
process.stdout.write(`${archive}\n`);
